POST http://localhost:4500/api/auth/RegisterForm
Content-Type: application/json

{
  "name": "shamee",
  "email": "zeenaathshameena@Gmail.com",
  "password": "Abcd234l",
  "userRole": "client"
}
####
POST http://localhost:4500/api/auth/Login
Content-Type: application/json

{
  "email": "shamee@Gmail.com",
  "password": "shamee"
}
####

POST http://localhost:4500/api/auth/submit
Content-Type: application/json

{
  "title": "Frss",
  "description": "asdfghjgdlxasx  niewinm jiwjijij iewjjewj...",
  "requirements": "efiuefhiu",
  "jobCategory": "full-time",
  "salary": 20000,
  "location": "Chennai",
  "workType": "onsite",
  "companyName": "ert2w",
  "email": "zeenathshameena@gmail.com",
  "jobFile": "1739263823267EmploymentCertificate.pdf",
  "dateTime": "2024-02-12"
}
####

GET http://localhost:4500/api/auth/Show_Works
####


PATCH  http://localhost:4500/api/auth/forgot-password
Content-Type: application/json

{
  "email": "zeenatha@gmail.com"
}
####
PATCH  http://localhost:4500/api/auth/verify-forgot-password-code
Content-Type: application/json

{
  "email": "zeenathshameena@gmail.com",
  "providedCode":310025,
  "newPassword":"Abcd3341"
}
####
get http://localhost:4500/api/auth/post
Content-Type: application/json

{
  "jobTitle": "Frss",
  "jobDescription": "asdfghjgdlxasiewjjewj...",
  "jobBudget": 1
}
####
get http://localhost:4500/api/auth/Available_Jobs


####
Post http://localhost:4500/api/auth/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2IxYjRhNjVlN2IwNDBlMGE1MDFhNDciLCJlbWFpbCI6InNoYW1lZUBnbWFpbC5jb20iLCJ1c2VyUm9sZSI6IkNsaWVudCIsImlhdCI6MTczOTcwMDc1MCwiZXhwIjoxNzM5NzI5NTUwfQ.M1loTenZxErZDK40oRIkuVOvDLweBasa5dDUyE6U3C8

{
  "name": "shamee",
  "email": "shameena@gmail.com.com",
  "company": "Tech Corp",
  "profileImage": "https://example.com/profile.jpg"
}
####
get http://localhost:4500/api/auth/profile